package coerce

import "github.com/ineffectivecoder/SMBGooser/pkg/dcerpc"

// knownInterfaces contains the pre-populated interface database
// Data sourced from MS-* specifications and security research
var knownInterfaces = []InterfaceInfo{
	// MS-EFSR - Encrypting File System Remote Protocol (PetitPotam)
	{
		Name:        "MS-EFSR",
		Description: "Encrypting File System Remote Protocol",
		UUID:        dcerpc.MustParseUUID("c681d488-d850-11d0-8c52-00c04fd90f7e"),
		Version:     1,
		Pipe:        "lsarpc",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "EfsRpcOpenFileRaw",
				PathParams: []PathParam{{Position: 1, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubHandlePath, Status: StatusConfirmed, Notes: "PetitPotam original - works on most systems"},
			{Opnum: 1, Name: "EfsRpcReadFileRaw",
				PathParams: []PathParam{},
				StubType:   StubHandleOnly, Status: StatusNegative, Notes: "Handle-based, no path"},
			{Opnum: 2, Name: "EfsRpcWriteFileRaw",
				PathParams: []PathParam{},
				StubType:   StubHandleOnly, Status: StatusNegative, Notes: "Handle-based, no path"},
			{Opnum: 3, Name: "EfsRpcCloseRaw",
				PathParams: []PathParam{},
				StubType:   StubHandleOnly, Status: StatusNegative, Notes: "Handle-based, no path"},
			{Opnum: 4, Name: "EfsRpcEncryptFileSrv",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "Works on unpatched systems"},
			{Opnum: 5, Name: "EfsRpcDecryptFileSrv",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "Works on unpatched systems"},
			{Opnum: 6, Name: "EfsRpcQueryUsersOnFile",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 7, Name: "EfsRpcQueryRecoveryAgents",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 8, Name: "EfsRpcRemoveUsersFromFile",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 9, Name: "EfsRpcAddUsersToFile",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 10, Name: "EfsRpcSetFileEncryptionKey",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 11, Name: "EfsRpcNotSupported",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "Not implemented"},
			{Opnum: 12, Name: "EfsRpcFileKeyInfo",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "Works on some systems"},
			{Opnum: 13, Name: "EfsRpcDuplicateEncryptionInfoFile",
				PathParams: []PathParam{
					{Position: 0, Name: "SrcFileName", Type: "wchar_t*"},
					{Position: 1, Name: "DestFileName", Type: "wchar_t*"},
				},
				StubType: StubTwoPath, Status: StatusCandidate, Notes: "Two path params"},
			{Opnum: 14, Name: "EfsRpcAddUsersToFileEx",
				PathParams: []PathParam{{Position: 1, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubFlagsPath, Status: StatusCandidate, Notes: "Has flags + path"},
			{Opnum: 15, Name: "EfsRpcFileKeyInfoEx",
				PathParams: []PathParam{{Position: 1, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubFlagsPath, Status: StatusCandidate, Notes: "Has flags + path"},
			{Opnum: 16, Name: "EfsRpcGetEncryptedFileMetadata",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 17, Name: "EfsRpcSetEncryptedFileMetadata",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has path param"},
			{Opnum: 18, Name: "EfsRpcFlushEfsCache",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 19, Name: "EfsRpcEncryptFileExSrv",
				PathParams: []PathParam{{Position: 0, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Extended encrypt"},
		},
	},

	// MS-RPRN - Print System Remote Protocol (PrinterBug/SpoolSample)
	{
		Name:        "MS-RPRN",
		Description: "Print System Remote Protocol",
		UUID:        dcerpc.MustParseUUID("12345678-1234-abcd-ef00-0123456789ab"),
		Version:     1,
		Pipe:        "spoolss",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "RpcEnumPrinters",
				PathParams: []PathParam{{Position: 2, Name: "Name", Type: "wchar_t*"}},
				StubType:   StubPrinterPath, Status: StatusCandidate, Notes: "Server name field"},
			{Opnum: 1, Name: "RpcOpenPrinter",
				PathParams: []PathParam{{Position: 0, Name: "pPrinterName", Type: "wchar_t*"}},
				StubType:   StubPrinterPath, Status: StatusCandidate, Notes: "Printer name"},
			{Opnum: 58, Name: "RpcRemoteFindFirstPrinterChangeNotificationEx",
				PathParams: []PathParam{{Position: 3, Name: "pszLocalMachine", Type: "wchar_t*"}},
				StubType:   StubPrinterNotify, Status: StatusConfirmed, Notes: "PrinterBug/SpoolSample - requires Print Spooler"},
			{Opnum: 65, Name: "RpcOpenPrinterEx",
				PathParams: []PathParam{{Position: 0, Name: "pPrinterName", Type: "wchar_t*"}},
				StubType:   StubPrinterPath, Status: StatusCandidate, Notes: "May accept UNC printer paths"},
			{Opnum: 69, Name: "RpcAddPrinterDriverEx",
				PathParams: []PathParam{{Position: 1, Name: "pDriverContainer", Type: "DRIVER_CONTAINER*"}},
				StubType:   StubEmpty, Status: StatusCandidate, Notes: "Driver path in container struct"},
		},
	},

	// MS-DFSNM - Distributed File System Namespace Management (DFSCoerce)
	{
		Name:        "MS-DFSNM",
		Description: "DFS Namespace Management Protocol",
		UUID:        dcerpc.MustParseUUID("4fc742e0-4a10-11cf-8273-00aa004ae673"),
		Version:     3,
		Pipe:        "netdfs",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "NetrDfsManagerGetVersion",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 12, Name: "NetrDfsAddStdRoot",
				PathParams: []PathParam{{Position: 0, Name: "ServerName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "DFSCoerce - requires DFS role"},
			{Opnum: 13, Name: "NetrDfsRemoveStdRoot",
				PathParams: []PathParam{{Position: 0, Name: "ServerName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "DFSCoerce variant"},
			{Opnum: 14, Name: "NetrDfsAddStdRootForced",
				PathParams: []PathParam{{Position: 0, Name: "ServerName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "DFSCoerce variant"},
			{Opnum: 19, Name: "NetrDfsGetInfo",
				PathParams: []PathParam{{Position: 0, Name: "DfsEntryPath", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Entry path could be UNC"},
			{Opnum: 20, Name: "NetrDfsSetInfo",
				PathParams: []PathParam{{Position: 0, Name: "DfsEntryPath", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Entry path could be UNC"},
			{Opnum: 21, Name: "NetrDfsGetClientInfo",
				PathParams: []PathParam{{Position: 0, Name: "DfsEntryPath", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Entry path could be UNC"},
		},
	},

	// MS-FSRVP - File Server Remote VSS Protocol (ShadowCoerce)
	{
		Name:        "MS-FSRVP",
		Description: "File Server Remote VSS Protocol",
		UUID:        dcerpc.MustParseUUID("a8e0653c-2744-4389-a61d-7373df8b2292"),
		Version:     1,
		Pipe:        "fssagentrpc",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "GetSupportedVersion",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 1, Name: "SetContext",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 2, Name: "StartShadowCopySet",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 3, Name: "AddToShadowCopySet",
				PathParams: []PathParam{{Position: 1, Name: "ShareName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Share name param"},
			{Opnum: 8, Name: "IsPathShadowCopied",
				PathParams: []PathParam{{Position: 0, Name: "ShareName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "ShadowCoerce - requires VSS service"},
			{Opnum: 9, Name: "GetShareMapping",
				PathParams: []PathParam{{Position: 0, Name: "ShareName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusConfirmed, Notes: "ShadowCoerce variant"},
			{Opnum: 10, Name: "DeleteShareMapping",
				PathParams: []PathParam{{Position: 0, Name: "ShareName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has ShareName param"},
			{Opnum: 11, Name: "IsPathSupported",
				PathParams: []PathParam{{Position: 0, Name: "ShareName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Has ShareName param"},
		},
	},

	// MS-EVEN - EventLog Remoting Protocol
	{
		Name:        "MS-EVEN",
		Description: "EventLog Remoting Protocol",
		UUID:        dcerpc.MustParseUUID("82273fdc-e32a-18c3-3f78-827929dc23ea"),
		Version:     0,
		Pipe:        "eventlog",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "ElfrClearELFW",
				PathParams: []PathParam{{Position: 1, Name: "BackupFileName", Type: "PRPC_UNICODE_STRING"}},
				StubType:   StubRPCUnicodeString, Status: StatusCandidate, Notes: "Clears log to backup path"},
			{Opnum: 7, Name: "ElfrBackupELFW",
				PathParams: []PathParam{{Position: 1, Name: "BackupFileName", Type: "PRPC_UNICODE_STRING"}},
				StubType:   StubRPCUnicodeString, Status: StatusCandidate, Notes: "Backs up log to path"},
			{Opnum: 11, Name: "ElfrOpenELW",
				PathParams: []PathParam{{Position: 1, Name: "LogName", Type: "PRPC_UNICODE_STRING"}},
				StubType:   StubRPCUnicodeString, Status: StatusCandidate, Notes: "Opens event log"},
			{Opnum: 12, Name: "ElfrOpenBELW",
				PathParams: []PathParam{{Position: 1, Name: "BackupFileName", Type: "PRPC_UNICODE_STRING"}},
				StubType:   StubRPCUnicodeString, Status: StatusCandidate, Notes: "Opens backup event log"},
		},
	},

	// MS-SCMR - Service Control Manager Remote Protocol
	{
		Name:        "MS-SCMR",
		Description: "Service Control Manager Remote Protocol",
		UUID:        dcerpc.MustParseUUID("367abb81-9844-35f1-ad32-98f038001003"),
		Version:     2,
		Pipe:        "svcctl",
		Methods: []MethodInfo{
			{Opnum: 12, Name: "RChangeServiceConfigW",
				PathParams: []PathParam{{Position: 3, Name: "lpBinaryPathName", Type: "wchar_t*"}},
				StubType:   StubSCMPath, Status: StatusCandidate, Notes: "Change service binary path"},
			{Opnum: 15, Name: "RCreateServiceW",
				PathParams: []PathParam{
					{Position: 7, Name: "lpBinaryPathName", Type: "wchar_t*"},
					{Position: 9, Name: "lpLoadOrderGroup", Type: "wchar_t*"},
				},
				StubType: StubSCMCreate, Status: StatusCandidate, Notes: "Binary path could be UNC"},
			{Opnum: 24, Name: "RCreateServiceWOW64W",
				PathParams: []PathParam{{Position: 7, Name: "lpBinaryPathName", Type: "wchar_t*"}},
				StubType:   StubSCMCreate, Status: StatusCandidate, Notes: "WOW64 variant"},
		},
	},

	// MS-WKST - Workstation Service Remote Protocol
	{
		Name:        "MS-WKST",
		Description: "Workstation Service Remote Protocol",
		UUID:        dcerpc.MustParseUUID("6bffd098-a112-3610-9833-46c3f87e345a"),
		Version:     1,
		Pipe:        "wkssvc",
		Methods: []MethodInfo{
			{Opnum: 13, Name: "NetrUseAdd",
				PathParams: []PathParam{{Position: 1, Name: "UncServerName", Type: "USE_INFO*"}},
				StubType:   StubUseInfo, Status: StatusCandidate, Notes: "UNC path for network use"},
			{Opnum: 23, Name: "NetrJoinDomain2",
				PathParams: []PathParam{{Position: 1, Name: "DomainName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Domain name could trigger lookup"},
		},
	},

	// MS-TSCH - Task Scheduler Service Remote Protocol
	{
		Name:        "MS-TSCH",
		Description: "Task Scheduler Service Remote Protocol",
		UUID:        dcerpc.MustParseUUID("86d35949-83c9-4044-b424-db363231fd0c"),
		Version:     1,
		Pipe:        "atsvc",
		Methods: []MethodInfo{
			{Opnum: 1, Name: "SchRpcRegisterTask",
				PathParams: []PathParam{{Position: 2, Name: "xml", Type: "wchar_t*"}},
				StubType:   StubTaskXML, Status: StatusCandidate, Notes: "Task XML could contain UNC paths"},
		},
	},

	// MS-FAX - Fax Service Protocol
	{
		Name:        "MS-FAX",
		Description: "Fax Service Remote Protocol",
		UUID:        dcerpc.MustParseUUID("6099fc12-3eff-11d0-abd0-00c04fd91a4e"),
		Version:     4,
		Pipe:        "fax",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "FaxConnectFaxServer",
				PathParams: []PathParam{{Position: 0, Name: "MachineName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Machine name could be UNC"},
			{Opnum: 5, Name: "FaxOpenPort",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
			{Opnum: 13, Name: "FaxSendDocument",
				PathParams: []PathParam{{Position: 2, Name: "FileName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Document path"},
			{Opnum: 70, Name: "FaxGetConfiguration",
				PathParams: []PathParam{},
				StubType:   StubEmpty, Status: StatusNegative, Notes: "No path param"},
		},
	},

	// MS-ICPR - Certificate Services Remote Protocol
	{
		Name:        "MS-ICPR",
		Description: "Certificate Services Remote Protocol",
		UUID:        dcerpc.MustParseUUID("91ae6020-9e3c-11cf-8d7c-00aa00c091be"),
		Version:     0,
		Pipe:        "cert",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "CertServerRequest",
				PathParams: []PathParam{{Position: 1, Name: "pwszAuthority", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Authority name"},
		},
	},

	// MS-SRVS - Server Service Remote Protocol (extended)
	{
		Name:        "MS-SRVS",
		Description: "Server Service Remote Protocol",
		UUID:        dcerpc.MustParseUUID("4b324fc8-1670-01d3-1278-5a47bf6ee188"),
		Version:     3,
		Pipe:        "srvsvc",
		Methods: []MethodInfo{
			{Opnum: 16, Name: "NetrShareAdd",
				PathParams: []PathParam{{Position: 2, Name: "ShareInfo", Type: "SHARE_INFO*"}},
				StubType:   StubShareInfo, Status: StatusCandidate, Notes: "Share path in info struct"},
			{Opnum: 28, Name: "NetrpPathType",
				PathParams: []PathParam{{Position: 1, Name: "PathName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Path type check"},
			{Opnum: 31, Name: "NetrPathCanonicalize",
				PathParams: []PathParam{{Position: 1, Name: "PathName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Path canonicalization"},
			{Opnum: 32, Name: "NetrPathCompare",
				PathParams: []PathParam{
					{Position: 1, Name: "PathName1", Type: "wchar_t*"},
					{Position: 2, Name: "PathName2", Type: "wchar_t*"},
				},
				StubType: StubTwoPath, Status: StatusCandidate, Notes: "Compare two paths"},
		},
	},

	// MS-NRPC - Netlogon Remote Protocol
	{
		Name:        "MS-NRPC",
		Description: "Netlogon Remote Protocol",
		UUID:        dcerpc.MustParseUUID("12345678-1234-abcd-ef00-01234567cffb"),
		Version:     1,
		Pipe:        "netlogon",
		Methods: []MethodInfo{
			{Opnum: 4, Name: "NetrServerReqChallenge",
				PathParams: []PathParam{{Position: 0, Name: "PrimaryName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Primary server name"},
			{Opnum: 30, Name: "NetrServerGetTrustInfo",
				PathParams: []PathParam{{Position: 0, Name: "TrustedDcName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Trusted DC name"},
		},
	},

	// MS-PAR - Print Async Notification Remote Protocol
	{
		Name:        "MS-PAR",
		Description: "Print Async Notification Remote Protocol",
		UUID:        dcerpc.MustParseUUID("76f03f96-cdfd-44fc-a22c-64950a001209"),
		Version:     1,
		Pipe:        "spoolss",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "AsyncOpenPrinter",
				PathParams: []PathParam{{Position: 0, Name: "pPrinterName", Type: "wchar_t*"}},
				StubType:   StubPrinterPath, Status: StatusCandidate, Notes: "Printer name"},
		},
	},

	// IRemoteWinspool
	{
		Name:        "IRemoteWinspool",
		Description: "Remote Winspool Interface",
		UUID:        dcerpc.MustParseUUID("9940ca8e-512f-4c58-88a9-61098d6896bd"),
		Version:     1,
		Pipe:        "spoolss",
		Methods: []MethodInfo{
			{Opnum: 0, Name: "RpcAsyncOpenPrinter",
				PathParams: []PathParam{{Position: 0, Name: "pPrinterName", Type: "wchar_t*"}},
				StubType:   StubPrinterPath, Status: StatusCandidate, Notes: "Async printer open"},
			{Opnum: 60, Name: "RpcAsyncRemoteFindFirstPrinterChangeNotification",
				PathParams: []PathParam{{Position: 3, Name: "pszLocalMachine", Type: "wchar_t*"}},
				StubType:   StubPrinterNotify, Status: StatusCandidate, Notes: "Async PrinterBug variant"},
		},
	},

	// MS-DNSP - DNS Server Management Protocol
	{
		Name:        "MS-DNSP",
		Description: "DNS Server Management Protocol",
		UUID:        dcerpc.MustParseUUID("50abc2a4-574d-40b3-9d66-ee4fd5fba076"),
		Version:     5,
		Pipe:        "dnsserver",
		Methods: []MethodInfo{
			{Opnum: 1, Name: "R_DnssrvOperation",
				PathParams: []PathParam{{Position: 1, Name: "pwszServerName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Server name"},
			{Opnum: 3, Name: "R_DnssrvEnumRecords",
				PathParams: []PathParam{{Position: 1, Name: "pwszServerName", Type: "wchar_t*"}},
				StubType:   StubSinglePath, Status: StatusCandidate, Notes: "Server name"},
		},
	},
}
